#!/bin/bash
export SCRIPTPATH="$(cd "$(dirname "$0")" ; pwd -P)"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill $SCRIPTPATH/background.jpg
fi

#boot picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom --config $HOME/.config/picom/picom.conf -b &>/dev/null &
  #picom -b &> /dev/null &
fi


if [ -x "$(command -v picom)" ]; then
  picom --config $HOME/.config/picom/picom.conf -b &>/dev/null &
  #picom -b &> /dev/null &
fi

#some startup app

if [ -x "$(command -v picom)" ]; then
  dunst --config $HOME/.config/dunst/dunstrc &
fi

nm-applet &

gnome-keyring-daemon --start --components=pkcs11 &

# xfce4-power-manager &
#boot polybar based on the number of monitors found
if [ -x "$(command -v polybar)" ]; then
  pkill polybar

  index=0
  monitors="$(polybar -m | sed s/:.*// | tac)"

  while read -r display; do
    bar="mainbar$index"
    MONITOR=$display polybar -c "$SCRIPTPATH/polybar.conf" $bar &> /dev/null &
    let index=index+1
  done <<< "$monitors"
  exit 0
fi

# rm -f $HOME/.config/eww
# ln -s $HOME/.config/left_eww $HOME/.config/eww

# eww  -c "$HOME/.config/eww/bar" --restart  open bar &
eww daemon &

$HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &
$HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &
$HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &
$HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &
#index=0
#sizes=( $(leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' ) )
#for size in "${sizes[@]}"
#do
#  eww open bar$index
#  let index=index+1
#done
