startup = [
 "zoxide init nushell --hook prompt | save ~/.zoxide.nu", "source ~/.zoxide.nu",
 "mkdir ~/.cache/starship",
 "starship init nu | save ~/.cache/starship/init.nu",
 "source ~/.cache/starship/init.nu"
]
prompt = "starship_prompt"
[env]
ABBR_TIPS_PROMPT = "\\n💡 \\e[1m{{ .abbr }}\\e[0m => {{ .cmd }}"
ABBR_TIPS_REGEXES = "(^(\\w+\\s+)+(-{1,2})\\w+)(\\s\\S+) (^(\\s?(\\w-?)+){3}).* (^(\\s?(\\w-?)+){2}).* (^(\\s?(\\w-?)+){1}).*"
BUNDLER_EDITOR = "nvim"
CMD_DURATION = "2.10606ms"
COLORTERM = "truecolor"
DOTFILES = "/Users/ray.xu/dotfiles"
EDITOR = "nvim"
FZF_ALT_C_COMMAND = "fd --type d . --color=never"
FZF_CTRL_T_COMMAND = "rg --files --hidden --follow --no-ignore-vcs"
FZF_DEFAULT_COMMAND = "rg --files --hidden --follow --no-ignore-vcs"
FZF_DEFAULT_OPTS = "--height 50% --layout=reverse --border"
GO111MODULE = "on"
GO2GO_DEST = "/Users/ray.xu/go/src/github.com/go2"
GO2PATH = "/Users/ray.xu/go/src/github.com/go2/src/cmd/go2go/testdata/go2path"
GOBIN = "/Users/ray.xu/go/bin"
GOPATH = "/Users/ray.xu/go"
GOPRIVATE = "github.com/deltatre-vxp"
GOROOT = "/Users/ray.xu/go/src/github.com/go2"
GRADLE_HOME = "/Users/ray.xu/gradle"
HOME = "/Users/ray.xu"
HOMEBREW_CASK_OPTS = "--appdir=/Applications"
HOST_NAME = "RayMac"
JAR = "/Users/ray.xu/lsp_test/jdt-language-server-0.70.0-202103051608/plugins/#"
JAVA_HOME = "/usr/local/Cellar/openjdk/15.0.2/"
JDTLS_CONFIG = "/Users/ray.xu/lsp_test/jdt-language-server-0.70.0-202103051608/config_mac"
KITTY_LISTEN_ON = "unix:/tmp/mykitty-"
KITTY_WINDOW_ID = "23"
LANG = "en_AU.UTF-8"
LOGNAME = "ray.xu"
MANPAGER = "less -X"
NVM_DIR = "/Users/ray.xu/.nvm"
PWD = "/Users/ray.xu/github/navigator.lua"
RUBY_CONFIGURE_OPTS = "--with-opt-dir=/usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/byaml:/usr/# local/opt/gdbm"
SHELL = "/bin/zsh"
SHLVL = "1"
SKIM_DEFAULT_COMMAND = "fd --type f || git ls-tree -r --name-only HEAD || rg --files || find ."
SOURCE_ANNOTATION_DIRECTORIES = "spec"
SSH_AGENT_PID = "21812"
SSH_AUTH_SOCK = "/var/folders/j_/q1hrp3lj619d06gp1_z7jcjr0000gp/T//ssh-13oIXPozFbCu/agent.21810"
SSH_ENV = "/Users/ray.xu/.ssh/environment"
STARSHIP_SESSION_KEY = "7759971416086371"
TERM = "xterm-kitty"
TERMINFO = "/Users/ray.xu/software/kitty/kitty.app/Contents/Resources/kitty/terminfo"
TERM_ITALICS = "true"
TMPDIR = "/var/folders/j_/q1hrp3lj619d06gp1_z7jcjr0000gp/T/"
USER = "ray.xu"
WINDOWID = "42210"
WORKSPACE = "/Users/ray.xu/workspace"
XDG_CACHE_HOME = "/Users/ray.xu/.cache"
XDG_CONFIG_HOME = "/Users/ray.xu/.config"
XDG_DATA_HOME = "/Users/ray.xu/.local/share"
XPC_FLAGS = "0x0"
XPC_SERVICE_NAME = "net.kovidgoyal.kitty.75060"
__ABBR_TIPS_KEYS = "cdgtop g gaa gap gash gasha gashl gashp gashu gau gc gce gcef gcl gcmsg gdf gdnw gdw gf gfa gfr glg gm gmff gmnff gopen gpl gplr gps gpsf gr grb grbi grs grsh grsl gsh gt gtop gurl runsv a__RM a__fish_key_reader a__fzf a__gdv a__gvim a__icat a__ll a__ls a__nd a__nm a__nv a__rm a__seperator a__sk a__vdiff a__gd"
__ABBR_TIPS_VALUES = "cd (git rev-parse --show-toplevel) git git add --all git add -pu git stash git stash apply git stash list git stash pop git stash --include-untracked git add -u git commit git clean git clean -fd git clone git commit -m git diff -- git diff -w -- git diff --word-diff git fetch git fetch --all git fetch; and git rebase git log --graph --max-count=5 git merge git merge --ff git merge --no-ff git config --get remote.origin.url | xargs open git pull git pull --rebase git push git push --force-with-lease git remote -v git rebase git rebase -i git reset -- git reset --hard git reset HEAD~ git show git tag git rev-parse --show-toplevel git config --get remote.origin.url python -m SimpleHTTPServer /bin/rm /usr/local/Cellar/fish/HEAD-2fff121/bin/fish_key_reader fzf --preview \"bat {} --color=always\" git difftool --tool gvimdiff /usr/local/bin/mvim kitty +kitten icat ls -lG ls -G git difftool --tool nvimdiff /usr/local/bin/nvim -u ~/github/dotfiles/init.min /usr/local/bin/nvim echo\\\\\\ \\\\\\\"\\\\\\\\u001b\\\\\\[31m\\\\\\ trash-put\\\\\\ !\\\\\\ \\\\\\\\u001b\\\\\\[0m\\\\\\\"\\\\\\;\\\\\\ trash-put viu (echo $HOME\"/photos/\"(ls ~/photos |sort -R |tail -1)) sk --preview \"bat {} --color=always\" /usr/local/bin/nvim -d -u ~/github/dotfiles/init.min"
__CF_USER_TEXT_ENCODING = "0x1F6:0x0:0xF"
arr = ""
op = ""