
# Start configuration added by Zim install {{{
#
# User configuration sourced by interactive shells
#

# -----------------
# Zsh configuration
# -----------------

#
# History
#


HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.


#
# Input/output
#

# Set editor default keymap to emacs (`-e`) or vi (`-v`)
bindkey -e

# Prompt for spelling correction of commands.
#setopt CORRECT

# Customize spelling correction prompt.
#SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '

# Remove path separator from WORDCHARS.
WORDCHARS=${WORDCHARS//[\/]}


# --------------------
# Module configuration
# --------------------

#
# completion
#

# Set a custom path for the completion dump file.
# If none is provided, the default ${ZDOTDIR:-${HOME}}/.zcompdump is used.
#zstyle ':zim:completion' dumpfile "${ZDOTDIR:-${HOME}}/.zcompdump-${ZSH_VERSION}"

#
# git
#

# Set a custom prefix for the generated aliases. The default prefix is 'G'.
#zstyle ':zim:git' aliases-prefix 'g'

#
# input
#

# Append `../` to your input for each `.` you type after an initial `..`
#zstyle ':zim:input' double-dot-expand yes

#
# termtitle
#

# Set a custom terminal title format using prompt expansion escape sequences.
# See http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Simple-Prompt-Escapes
# If none is provided, the default '%n@%m: %~' is used.
#zstyle ':zim:termtitle' format '%1~'

#
# zsh-autosuggestions
#

# Customize the style that the suggestions are shown with.
# See https://github.com/zsh-users/zsh-autosuggestions/blob/master/README.md#suggestion-highlight-style
#ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'

#
# zsh-syntax-highlighting
#

# Set what highlighters will be used.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# Customize the main highlighter styles.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md#how-to-tweak-it
#typeset -A ZSH_HIGHLIGHT_STYLES
#ZSH_HIGHLIGHT_STYLES[comment]='fg=10'


zstyle ':zim:ssh' ids 'id_ed25519' 'id_ed25519_deltatre' 'id_ed25519_github_deltatre'

# ------------------
# Initialize modules
# ------------------

if [[ ${ZIM_HOME}/init.zsh -ot ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  # Update static initialization script if it's outdated, before sourcing it
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
source ${ZIM_HOME}/init.zsh

# ------------------------------
# Post-init module configuration
# ------------------------------

#
# zsh-history-substring-search
#

# Bind ^[[A/^[[B manually so up/down works both before and after zle-line-init
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Bind up and down keys
zmodload -F zsh/terminfo +p:terminfo
if [[ -n ${terminfo[kcuu1]} && -n ${terminfo[kcud1]} ]]; then
  bindkey ${terminfo[kcuu1]} history-substring-search-up
  bindkey ${terminfo[kcud1]} history-substring-search-down
fi

bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down


# --------------RAY CONFIG-----------------
export GOPATH="/Users/ray.xu/go"
export GOROOT="/usr/local/opt/go/libexec" # install with brew

# export GOROOT=/usr/local/go   # install with pkg download from golang.org
export GOBIN=$GOPATH/bin
export GO111MODULE="on"
export PATH=~/bin:/usr/local/bin:$HOME/.local/bin:$PATH
export PATH=$GOPATH/bin:$PATH
export PATH=$GOROOT/bin:$PATH
# export GOPRIVATE="bitbucket.org/appcurator,github.com/deltatre-vxp"
export GOPRIVATE="github.com/deltatre-vxp"

export GO2GO_DEST=$GOPATH/src/github.com/go2
export PATH="$GO2GO_DEST/bin:$PATH"
export GOROOT="$GO2GO_DEST"
export GO2PATH="$GO2GO_DEST/src/cmd/go2go/testdata/go2path"


export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$HOME/.cargo/bin:$PATH"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
alias gvim='/usr/local/bin/mvim'
alias nv='/usr/local/bin/nvim'
alias nm='/usr/local/bin/nvim -u ~/github/dotfiles/init.min'
alias vdiff='/usr/local/bin/nvim -d -u ~/github/dotfiles/init.min'
alias gdv='git difftool --tool gvimdiff'
alias nd='git difftool --tool nvimdiff'
alias ls='ls -G'
alias ll='ls -lG'
alias icat="kitty +kitten icat"
alias RM='/bin/rm'
export PATH="/usr/local/opt/python@3.9/bin:$PATH"
export PATH="/usr/local/opt/llvm/bin:/Users/ray.xu/github/dotfiles/bin/:$PATH"
autoload -Uz compinit
compinit
# Completion for kitty
kitty + complete setup zsh | source /dev/stdin
export TERM_ITALICS=true


export KITTY_LISTEN_ON=unix:/tmp/mykitty-$PPID
SKIM_DEFAULT_COMMAND="fd --type f || git ls-tree -r --name-only HEAD || rg --files || find ."

alias fzf='fzf --preview="bat {} --color=always"'
alias sk='sk --preview="bat {} --color=always"'
alias seperator='viu `echo ~/photos/$(ls ~/photos |sort -R |tail -1)`'
alias rm='echo "\u001b[31m trash-put ! \u001b[0m"; trash-put'

export JAR=$HOME/lsp_test/jdt-language-server-0.70.0-202103051608/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar
export GRADLE_HOME=$HOME/gradle
export JAVA_HOME=/usr/local/Cellar/openjdk/15.0.2/
export JDTLS_CONFIG=$HOME/lsp_test/jdt-language-server-0.70.0-202103051608/config_mac
export WORKSPACE=$HOME/workspace

export PATH=$PATH:JAVA_HOME/bin


# typeset -g POWERLEVEL9K_INSTANT_PROMPT=off
{eval "$(ssh-agent -s)"; ssh-add -K ~/.ssh/id_ed25519_github_deltatre}  2>/dev/null 1>/dev/null

# }}} End configuration added by Zim install


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.forgit.plugin.zsh ] && source ~/.forgit.plugin.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# To customize prompt, run `p10k configure` or edit ~/github/dotfiles/.p10k.zsh.
# [[ ! -f ~/github/dotfiles/.p10k.zsh ]] || source ~/github/dotfiles/.p10k.zsh

# source ~/.fzffun.zsh
eval "$(starship init zsh)"

alias luamake=/Users/ray.xu/github/sumneko/lua-language-server/3rd/luamake/luamake
